kind: Deployment
apiVersion: apps/v1
metadata:
  name: front
  namespace: doodle
  labels:
    k8s-app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: front
  template:
    metadata:
      name: front
      labels:
        k8s-app: front
    spec:
      containers:
        - name: front
          image: doordle.ovh/prod/doodle-api:latest
          imagePullPolicy: Never
          securityContext:
            privileged: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
kind: Service
apiVersion: v1
metadata:
  name: front
  namespace: doodle
  labels:
    k8s-app: front
spec:
  ports:
    - name: tcp-80-3000-front
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    k8s-app: front