kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  namespace: doodle
  labels:
    k8s-app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: api
  template:
    metadata:
      name: api
      labels:
        k8s-app: api
    spec:
      containers:
        - name: api
          image: doodle-api:0.1.0
          imagePullPolicy: Never
          securityContext:
            privileged: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: doodle
  labels:
    k8s-app: api
spec:
  ports:
    - name: tcp-8080-8080-api
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    k8s-app: api