# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."doodle-services-db" = {
    image = "mysql";
    environment = {
      "MYSQL_DATABASE" = "tlc";
      "MYSQL_PASSWORD" = "tlc";
      "MYSQL_ROOT_PASSWORD" = "root";
      "MYSQL_USER" = "tlc";
    };
    ports = [
      "3306:3306/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=doodle-services_default"
    ];
  };
  systemd.services."docker-doodle-services-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-doodle-services_default.service"
    ];
    requires = [
      "docker-network-doodle-services_default.service"
    ];
    partOf = [
      "docker-compose-doodle-services-root.target"
    ];
    wantedBy = [
      "docker-compose-doodle-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."doodle-services-etherpad" = {
    image = "etherpad/etherpad:latest";
    volumes = [
      "/home/titouan/Documents/ESIR/S8/DevOps/devops/nix/doodle/api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt:rw"
    ];
    ports = [
      "9001:9001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=etherpad"
      "--network=doodle-services_default"
    ];
  };
  systemd.services."docker-doodle-services-etherpad" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-doodle-services_default.service"
    ];
    requires = [
      "docker-network-doodle-services_default.service"
    ];
    partOf = [
      "docker-compose-doodle-services-root.target"
    ];
    wantedBy = [
      "docker-compose-doodle-services-root.target"
    ];
  };
  virtualisation.oci-containers.containers."doodle-services-mail" = {
    image = "bytemark/smtp";
    ports = [
      "2525:25/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mail"
      "--network=doodle-services_default"
    ];
  };
  systemd.services."docker-doodle-services-mail" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-doodle-services_default.service"
    ];
    requires = [
      "docker-network-doodle-services_default.service"
    ];
    partOf = [
      "docker-compose-doodle-services-root.target"
    ];
    wantedBy = [
      "docker-compose-doodle-services-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-doodle-services_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f doodle-services_default";
    };
    script = ''
      docker network inspect doodle-services_default || docker network create doodle-services_default
    '';
    partOf = [ "docker-compose-doodle-services-root.target" ];
    wantedBy = [ "docker-compose-doodle-services-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-doodle-services-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
