- name: Kubernetes cluster setup
  hosts: all
  become: yes
  roles:
    - common

- name: Kubernetes master init
  hosts: master
  become: yes
  roles:
    - master

- name: Kubernetes worker join
  hosts: workers
  become: yes
  roles:
    - worker

- name: Kubernetes deploy yaml
  hosts: master
  become: yes
  roles:
    - master-deploy