- name: Fetch join command from master
  fetch:
    src: /tmp/kubeadm_join.sh
    dest: /tmp/kubeadm_join.sh
    flat: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Copy join script to worker
  copy:
    src: /tmp/kubeadm_join.sh
    dest: /tmp/kubeadm_join.sh
    mode: 0755

- name: Join the cluster
  command: bash /tmp/kubeadm_join.sh